[package]
name = "bevy_pong"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies.bevy]
version = "0.15"
features = ["wayland"]

[dependencies]
avian2d = { version = "0.2" }
rand = { version = "0.8.5" }
